import io
import html
from datetime import datetime
from typing import Dict, Any, List, Optional, Tuple

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Rect, String, Group, Circle, Line
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.barcharts import VerticalBarChart, HorizontalBarChart
from reportlab.graphics.charts.legends import Legend


class PDFColors:
    # Primary & Dark
    PRIMARY_DARK = colors.HexColor('#0f172a')
    HEADING_DARK = colors.HexColor('#1e293b')
    BODY_TEXT = colors.HexColor('#334155')
    MUTED_TEXT = colors.HexColor('#64748b')
    LIGHT_TEXT = colors.HexColor('#94a3b8')
    WHITE = colors.HexColor('#ffffff')

    # Accent & Brand
    BRAND_BLUE = colors.HexColor('#2563eb')
    BRAND_BLUE_LIGHT = colors.HexColor('#eff6ff')
    BRAND_INDIGO = colors.HexColor('#4f46e5')
    BRAND_PURPLE = colors.HexColor('#7c3aed')
    BRAND_PURPLE_LIGHT = colors.HexColor('#faf5ff')

    # Status Badges & Metrics
    SUCCESS_GREEN = colors.HexColor('#10b981')
    SUCCESS_GREEN_DARK = colors.HexColor('#059669')
    SUCCESS_GREEN_BG = colors.HexColor('#ecfdf5')

    WARNING_AMBER = colors.HexColor('#f59e0b')
    WARNING_AMBER_DARK = colors.HexColor('#d97706')
    WARNING_AMBER_BG = colors.HexColor('#fffbeb')

    CRITICAL_RED = colors.HexColor('#ef4444')
    CRITICAL_RED_DARK = colors.HexColor('#dc2626')
    CRITICAL_RED_BG = colors.HexColor('#fef2f2')

    INFO_BLUE = colors.HexColor('#0284c7')
    INFO_BLUE_BG = colors.HexColor('#f0f9ff')

    # Card & Neutral Backgrounds
    BG_CARD = colors.HexColor('#f8fafc')
    BG_CARD_ALT = colors.HexColor('#f1f5f9')
    BG_CARD_DARK = colors.HexColor('#18181b')
    BORDER_LIGHT = colors.HexColor('#e2e8f0')
    BORDER_MED = colors.HexColor('#cbd5e1')
    BORDER_DARK = colors.HexColor('#27272a')


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas that adds professional running header and footer with total page count (Page X of Y)
    and executive branding rules.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(PDFColors.MUTED_TEXT)

        page_width, page_height = self._pagesize

        # Running Header on page 2 and later
        if self._pageNumber > 1:
            self.setFillColor(PDFColors.MUTED_TEXT)
            self.drawString(36, page_height - 24, "SEO INTELLIGENCE PLATFORM — EXECUTIVE AUDIT REPORT")
            self.drawRightString(page_width - 36, page_height - 24, datetime.now().strftime("%B %d, %Y"))
            self.setStrokeColor(PDFColors.BORDER_LIGHT)
            self.setLineWidth(0.75)
            self.line(36, page_height - 28, page_width - 36, page_height - 28)

        # Running Footer on all pages
        self.setStrokeColor(PDFColors.BORDER_LIGHT)
        self.setLineWidth(0.75)
        self.line(36, 32, page_width - 36, 32)

        self.setFillColor(PDFColors.MUTED_TEXT)
        self.drawString(36, 20, "Confidential — Generated by SEO Intelligence Platform")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(page_width - 36, 20, page_str)

        self.restoreState()


class EnterprisePDFTheme:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._init_custom_styles()

    def _init_custom_styles(self):
        self.cover_brand = ParagraphStyle(
            'CoverBrand',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=10,
            leading=12,
            textColor=PDFColors.BRAND_BLUE,
            spaceAfter=6
        )

        self.cover_title = ParagraphStyle(
            'CoverTitle',
            parent=self.styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=24,
            leading=28,
            textColor=PDFColors.PRIMARY_DARK,
            spaceAfter=6
        )

        self.cover_subtitle = ParagraphStyle(
            'CoverSubtitle',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=11,
            leading=15,
            textColor=PDFColors.MUTED_TEXT,
            spaceAfter=14
        )

        self.section_title = ParagraphStyle(
            'SectionTitle',
            parent=self.styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=PDFColors.PRIMARY_DARK,
            spaceBefore=14,
            spaceAfter=6,
            keepWithNext=True
        )

        self.section_subtitle = ParagraphStyle(
            'SectionSubtitle',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            leading=13,
            textColor=PDFColors.MUTED_TEXT,
            spaceAfter=8,
            keepWithNext=True
        )

        self.body = ParagraphStyle(
            'BodyTextCustom',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=13,
            textColor=PDFColors.BODY_TEXT
        )

        self.body_bold = ParagraphStyle(
            'BodyBoldCustom',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9,
            leading=13,
            textColor=PDFColors.PRIMARY_DARK
        )

        self.kpi_title = ParagraphStyle(
            'KPITitle',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=8,
            leading=10,
            textColor=PDFColors.MUTED_TEXT
        )

        self.kpi_value = ParagraphStyle(
            'KPIValue',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=18,
            leading=22,
            textColor=PDFColors.PRIMARY_DARK
        )

        self.kpi_sub = ParagraphStyle(
            'KPISub',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=7.5,
            leading=9,
            textColor=PDFColors.MUTED_TEXT
        )

        self.table_header = ParagraphStyle(
            'TableHeaderCustom',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=8.5,
            leading=11,
            textColor=PDFColors.PRIMARY_DARK
        )

        self.table_cell = ParagraphStyle(
            'TableCellCustom',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=8,
            leading=11,
            textColor=PDFColors.BODY_TEXT
        )

        self.table_cell_bold = ParagraphStyle(
            'TableCellBoldCustom',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=8,
            leading=11,
            textColor=PDFColors.PRIMARY_DARK
        )

        self.issue_header = ParagraphStyle(
            'IssueHeader',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9.5,
            leading=13,
            textColor=PDFColors.PRIMARY_DARK
        )

        self.issue_label = ParagraphStyle(
            'IssueLabel',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=8,
            leading=11,
            textColor=PDFColors.MUTED_TEXT
        )

        self.issue_text = ParagraphStyle(
            'IssueText',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=8.5,
            leading=12,
            textColor=PDFColors.BODY_TEXT
        )

        self.ai_recommendation = ParagraphStyle(
            'AIRec',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=8.5,
            leading=12,
            textColor=PDFColors.BRAND_BLUE
        )


class PDFComponentBuilder:
    """
    Enterprise PDF Component Builder rendering SEMrush / Ahrefs / HubSpot standard visuals.
    """
    def __init__(self, theme: EnterprisePDFTheme = None):
        self.theme = theme or EnterprisePDFTheme()

    def build_header_banner(
        self,
        story: list,
        report_title: str,
        domain: str,
        project_name: str,
        crawl_timestamp: str = "N/A",
        data_sources: str = "Automated Website Scan & SEO Auditing Engine",
        health_score: int = 100
    ):
        now_str = datetime.now().strftime("%d %B %Y, %I:%M %p")

        # Top Category Brand Pill
        story.append(Paragraph("SEO INTELLIGENCE PLATFORM • EXECUTIVE REPORT", self.theme.cover_brand))
        story.append(Paragraph(report_title, self.theme.cover_title))
        story.append(Paragraph(f"Target Website: <b>{domain}</b> &nbsp;|&nbsp; Project: <b>{project_name}</b>", self.theme.cover_subtitle))
        story.append(HRFlowable(width="100%", thickness=2, color=PDFColors.BRAND_BLUE, spaceAfter=10, spaceBefore=0))

        # Metadata Card Grid
        meta_data = [
            [
                Paragraph("<b>Website Domain:</b>", self.theme.table_header),
                Paragraph(domain or "Website", self.theme.table_cell),
                Paragraph("<b>Report Generated:</b>", self.theme.table_header),
                Paragraph(now_str, self.theme.table_cell)
            ],
            [
                Paragraph("<b>Project Name:</b>", self.theme.table_header),
                Paragraph(project_name or "SEO Audit", self.theme.table_cell),
                Paragraph("<b>Crawl Scan Date:</b>", self.theme.table_header),
                Paragraph(crawl_timestamp or "N/A", self.theme.table_cell)
            ],
            [
                Paragraph("<b>Data Engine:</b>", self.theme.table_header),
                Paragraph(data_sources, self.theme.table_cell),
                Paragraph("<b>Overall Health:</b>", self.theme.table_header),
                Paragraph(f"<font color='{self._get_health_color_hex(health_score)}'><b>{health_score} / 100</b></font>", self.theme.table_header)
            ]
        ]
        t_meta = Table(meta_data, colWidths=[105, 165, 105, 165])
        t_meta.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), PDFColors.BG_CARD),
            ('GRID', (0, 0), (-1, -1), 0.5, PDFColors.BORDER_LIGHT),
            ('PADDING', (0, 0), (-1, -1), 4.5),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        story.append(t_meta)
        story.append(Spacer(1, 12))

    def _get_health_color_hex(self, score: int) -> str:
        if score >= 85:
            return "#10b981"
        elif score >= 60:
            return "#f59e0b"
        return "#ef4444"

    def build_kpi_grid(self, story: list, kpis: List[Dict[str, Any]]):
        """
        Builds a 4-column executive KPI card grid with high-contrast metric values and color status indicators.
        """
        rows = []
        # Chunk into rows of 4
        chunk_size = 4
        for i in range(0, len(kpis), chunk_size):
            chunk = kpis[i:i + chunk_size]
            row_cells = []
            for item in chunk:
                title = item.get("title", "METRIC").upper()
                value = str(item.get("value", "0"))
                subtext = item.get("subtext", "")
                val_color = item.get("color", "#0f172a")

                val_style = ParagraphStyle(
                    f'ValStyle_{title}_{i}',
                    parent=self.theme.kpi_value,
                    textColor=colors.HexColor(val_color) if isinstance(val_color, str) and val_color.startswith("#") else val_color
                )

                card_content = [
                    Paragraph(title, self.theme.kpi_title),
                    Spacer(1, 2),
                    Paragraph(value, val_style),
                    Spacer(1, 2),
                    Paragraph(subtext, self.theme.kpi_sub)
                ]
                row_cells.append(card_content)

            # Pad row if less than 4
            while len(row_cells) < 4:
                row_cells.append([Paragraph("", self.theme.body)])

            rows.append(row_cells)

        t_kpi = Table(rows, colWidths=[135, 135, 135, 135])
        t_kpi.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), PDFColors.BG_CARD),
            ('BOX', (0, 0), (-1, -1), 0.75, PDFColors.BORDER_MED),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, PDFColors.BORDER_LIGHT),
            ('PADDING', (0, 0), (-1, -1), 7),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        story.append(t_kpi)
        story.append(Spacer(1, 12))

    def build_vector_issue_chart(self, crit: int, warn: int, notice: int, passed: int) -> Drawing:
        """
        Creates a native vector chart visualizing the issue & audit distribution.
        """
        d = Drawing(540, 110)
        # Background container
        d.add(Rect(0, 0, 540, 110, fillColor=PDFColors.BG_CARD, strokeColor=PDFColors.BORDER_LIGHT, strokeWidth=0.5, rx=6, ry=6))

        # Title
        d.add(String(16, 90, "AUDIT FINDINGS DISTRIBUTION", fontName="Helvetica-Bold", fontSize=9, fillColor=PDFColors.MUTED_TEXT))

        # Total issues count
        total = crit + warn + notice + passed
        if total == 0:
            total = 1

        # Vector Horizontal Multi-Segment Progress Bar
        bar_x = 16
        bar_y = 55
        bar_w = 508
        bar_h = 22

        # Draw background bar
        d.add(Rect(bar_x, bar_y, bar_w, bar_h, fillColor=PDFColors.BORDER_LIGHT, strokeColor=None, rx=4, ry=4))

        crit_w = (crit / total) * bar_w
        warn_w = (warn / total) * bar_w
        notice_w = (notice / total) * bar_w
        passed_w = (passed / total) * bar_w

        curr_x = bar_x
        if crit_w > 0:
            d.add(Rect(curr_x, bar_y, crit_w, bar_h, fillColor=PDFColors.CRITICAL_RED, strokeColor=None))
            curr_x += crit_w
        if warn_w > 0:
            d.add(Rect(curr_x, bar_y, warn_w, bar_h, fillColor=PDFColors.WARNING_AMBER, strokeColor=None))
            curr_x += warn_w
        if notice_w > 0:
            d.add(Rect(curr_x, bar_y, notice_w, bar_h, fillColor=PDFColors.INFO_BLUE, strokeColor=None))
            curr_x += notice_w
        if passed_w > 0:
            d.add(Rect(curr_x, bar_y, passed_w, bar_h, fillColor=PDFColors.SUCCESS_GREEN, strokeColor=None))

        # Legend items at bottom
        leg_y = 20
        # Critical
        d.add(Circle(22, leg_y + 4, 4, fillColor=PDFColors.CRITICAL_RED, strokeColor=None))
        d.add(String(32, leg_y, f"Critical Issues: {crit}", fontName="Helvetica-Bold", fontSize=8, fillColor=PDFColors.PRIMARY_DARK))

        # Warning
        d.add(Circle(160, leg_y + 4, 4, fillColor=PDFColors.WARNING_AMBER, strokeColor=None))
        d.add(String(170, leg_y, f"Warnings: {warn}", fontName="Helvetica-Bold", fontSize=8, fillColor=PDFColors.PRIMARY_DARK))

        # Notices
        d.add(Circle(285, leg_y + 4, 4, fillColor=PDFColors.INFO_BLUE, strokeColor=None))
        d.add(String(295, leg_y, f"Notices / Info: {notice}", fontName="Helvetica-Bold", fontSize=8, fillColor=PDFColors.PRIMARY_DARK))

        # Passed
        d.add(Circle(410, leg_y + 4, 4, fillColor=PDFColors.SUCCESS_GREEN, strokeColor=None))
        d.add(String(420, leg_y, f"Passed Checks: {passed}", fontName="Helvetica-Bold", fontSize=8, fillColor=PDFColors.PRIMARY_DARK))

        return d

    def build_issue_card(self, story: list, idx: int, issue: Dict[str, Any]):
        """
        Creates an executive issue card with severity badge pill, affected URL, evidence, why it matters, and AI solutions.
        """
        sev = str(issue.get("severity") or issue.get("priority") or "Warning").upper()
        if sev in ("CRITICAL", "FATAL", "ERROR"):
            badge_bg = PDFColors.CRITICAL_RED_BG
            badge_color = PDFColors.CRITICAL_RED_DARK
            border_color = PDFColors.CRITICAL_RED
        elif sev in ("HIGH", "WARNING", "MEDIUM"):
            badge_bg = PDFColors.WARNING_AMBER_BG
            badge_color = PDFColors.WARNING_AMBER_DARK
            border_color = PDFColors.WARNING_AMBER
        else:
            badge_bg = PDFColors.INFO_BLUE_BG
            badge_color = PDFColors.INFO_BLUE
            border_color = PDFColors.INFO_BLUE

        prob_title = html.escape(str(issue.get("problem") or issue.get("title") or issue.get("issue") or "Detected SEO Issue"))
        url = html.escape(str(issue.get("affected_url") or issue.get("url") or "-"))
        found = html.escape(str(issue.get("what_was_found") or issue.get("evidence") or issue.get("description") or "Identified during crawl inspection."))
        why = html.escape(str(issue.get("why_it_matters") or "Impacts search engine crawl efficiency, content indexability, or keyword ranking relevance."))
        action = html.escape(str(issue.get("recommended_action") or issue.get("recommendation") or "Review and resolve affected page element."))
        ai_sol = html.escape(str(issue.get("ai_solution") or action or "Deploy targeted on-page metadata and structural fixes."))

        badge_p = Paragraph(f"<font color='{badge_color.hexval()}'><b>{sev}</b></font>", self.theme.table_header)
        title_p = Paragraph(f"<b>{idx}. {prob_title}</b>", self.theme.issue_header)

        header_table = Table([[title_p, badge_p]], colWidths=[460, 60])
        header_table.setStyle(TableStyle([
            ('ALIGN', (1, 0), (1, 0), 'RIGHT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('PADDING', (0, 0), (-1, -1), 0),
        ]))

        content_rows = [
            [header_table],
            [HRFlowable(width="100%", thickness=0.5, color=PDFColors.BORDER_LIGHT, spaceAfter=4, spaceBefore=4)],
            [Paragraph(f"<b>Affected URL:</b> <font color='#2563eb'>{url}</font>", self.theme.issue_text)],
            [Paragraph(f"<b>What We Found:</b> {found}", self.theme.issue_text)],
            [Paragraph(f"<b>Why It Matters:</b> {why}", self.theme.issue_text)],
            [Paragraph(f"<b>Recommended Action:</b> {action}", self.theme.issue_text)],
            [Paragraph(f"<b>AI Action Plan:</b> <font color='#2563eb'>{ai_sol}</font> <i>(Evidence Grounded)</i>", self.theme.ai_recommendation)]
        ]

        t_card = Table(content_rows, colWidths=[520])
        t_card.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), PDFColors.BG_CARD),
            ('BOX', (0, 0), (-1, -1), 0.75, border_color),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))

        story.append(t_card)
        story.append(Spacer(1, 7))

    def build_styled_table(self, headers: List[str], rows: List[List[Any]], col_widths: List[float], max_rows: int = 50) -> Table:
        """
        Creates an executive styled table with crisp borders, shaded header, and alternating rows.
        """
        table_data = [[Paragraph(f"<b>{h}</b>", self.theme.table_header) for h in headers]]

        display_rows = rows[:max_rows] if max_rows else rows
        for row in display_rows:
            formatted_row = []
            for cell in row:
                if isinstance(cell, Paragraph):
                    formatted_row.append(cell)
                else:
                    formatted_row.append(Paragraph(html.escape(str(cell if cell is not None else "-")), self.theme.table_cell))
            table_data.append(formatted_row)

        t = Table(table_data, colWidths=col_widths)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), PDFColors.BG_CARD_ALT),
            ('GRID', (0, 0), (-1, -1), 0.5, PDFColors.BORDER_LIGHT),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [PDFColors.WHITE, PDFColors.BG_CARD]),
            ('PADDING', (0, 0), (-1, -1), 4.5),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        return t

    def build_roadmap_table(self, story: list):
        """
        Generates a visual phased SEO execution roadmap.
        """
        roadmap_data = [
            [
                Paragraph("<b>Timeframe</b>", self.theme.table_header),
                Paragraph("<b>Focus Domain</b>", self.theme.table_header),
                Paragraph("<b>Recommended Execution Action</b>", self.theme.table_header),
                Paragraph("<b>Expected Business Impact</b>", self.theme.table_header)
            ],
            [
                Paragraph("<font color='#ef4444'><b>NOW (0–7 Days)</b></font>", self.theme.table_header),
                Paragraph("Critical Crawlability & HTTP Status", self.theme.table_cell_bold),
                Paragraph("Repair broken 404 links, fix 500 server errors, resolve canonical conflicts, and unblock key pages.", self.theme.table_cell),
                Paragraph("Restores search engine access and prevents rank drops.", self.theme.table_cell)
            ],
            [
                Paragraph("<font color='#f59e0b'><b>NEXT 30 DAYS</b></font>", self.theme.table_header),
                Paragraph("On-Page SEO & Metadata", self.theme.table_cell_bold),
                Paragraph("Optimize missing title tags (30–60 chars), add compelling meta descriptions, and enforce single H1 headings.", self.theme.table_cell),
                Paragraph("Boosts SERP CTR and ranking relevance.", self.theme.table_cell)
            ],
            [
                Paragraph("<font color='#2563eb'><b>NEXT 60–90 DAYS</b></font>", self.theme.table_header),
                Paragraph("Content Depth & Link Architecture", self.theme.table_cell_bold),
                Paragraph("Expand thin pages (< 300 words), build contextual internal links with descriptive anchors, and target keyword gaps.", self.theme.table_cell),
                Paragraph("Improves topical authority and PageRank flow.", self.theme.table_cell)
            ],
            [
                Paragraph("<font color='#10b981'><b>ONGOING</b></font>", self.theme.table_header),
                Paragraph("Monitoring & Authority", self.theme.table_cell_bold),
                Paragraph("Schedule automated weekly crawls, monitor Google Search Console positions, and track new backlinks.", self.theme.table_cell),
                Paragraph("Protects organic traffic and catches regressions.", self.theme.table_cell)
            ]
        ]

        t_road = Table(roadmap_data, colWidths=[100, 120, 190, 130])
        t_road.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), PDFColors.BG_CARD_ALT),
            ('GRID', (0, 0), (-1, -1), 0.5, PDFColors.BORDER_LIGHT),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [PDFColors.WHITE, PDFColors.BG_CARD]),
            ('PADDING', (0, 0), (-1, -1), 5),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        story.append(t_road)
        story.append(Spacer(1, 12))
